title: Justin Choi
email: jchoi@mit.edu
baseurl: ""
url: ""

# page setup
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: just-the-docs
color_scheme: dismint
plugins:
  - jekyll-feed

# config options
callouts:
  warning:
    title: Warning
    color: green
    opacity: 0.8

# code setup
enable_copy_code_button: true

